<?php

/**
 * @file
 * Main module file for Commerce postal code filter User interface
 */

/**
 * Implements hook_menu().
 */
function commerce_postal_code_filter_ui_menu() {

  $items = array();

  $items['admin/commerce/config/postal-code-filter'] = array(
    'title' => 'Postal code filter',
    'description' => 'Administer the postal code filter (blacklist or whitelist postal codes).',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_postal_code_filter_ui_configure'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('configure postal code filter'),
    'file' => 'commerce_postal_code_filter_ui.admin.inc',
  );

  return $items;

}

/**
 * Implements hook_permission().
 */
function commerce_postal_code_filter_ui_permission() {
  return array(
    'configure postal code filter' => array(
      'title' => t('Configure postal code filter'),
      'description' => t('Edit the list of postal codes on the blacklist or whitelist.'),
    ),
  );
}

/**
 * Implements hook_commerce_postal_code_filter_postal_codes().
 *
 * Fetch the postal codes from the variable and return them to the core module
 *
 * @return array
 *   List of postal codes to filter
 */
function commerce_postal_code_filter_ui_commerce_postal_code_filter_postal_codes() {

  $postal_codes = variable_get('commerce_postal_code_filter_postal_codes', '');
  return explode(',', $postal_codes);

}
